name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/60 * * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Auto green
        run: |
          git config --local user.email "1847261658@qq.com"
          git config --local user.name "SUNWUYUAN"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "知识创造一切"
          git push
